/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectTenantRouteImport } from './routes/select-tenant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppConsultaRouteImport } from './routes/app.consulta'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AppVentasIndexRouteImport } from './routes/app.ventas.index'
import { Route as AppProductosIndexRouteImport } from './routes/app.productos.index'
import { Route as AppInventarioIndexRouteImport } from './routes/app.inventario.index'
import { Route as AdminTenantsIndexRouteImport } from './routes/admin.tenants.index'
import { Route as AppProductosNuevoRouteImport } from './routes/app.productos.nuevo'
import { Route as AppProductosProductIdRouteImport } from './routes/app.productos.$productId'
import { Route as AppInventarioSalidaRouteImport } from './routes/app.inventario.salida'
import { Route as AppInventarioMovimientosRouteImport } from './routes/app.inventario.movimientos'
import { Route as AppInventarioEntradaRouteImport } from './routes/app.inventario.entrada'
import { Route as AdminTenantsNewRouteImport } from './routes/admin.tenants.new'
import { Route as AdminTenantsIdRouteImport } from './routes/admin.tenants.$id'

const SelectTenantRoute = SelectTenantRouteImport.update({
  id: '/select-tenant',
  path: '/select-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultaRoute = AppConsultaRouteImport.update({
  id: '/consulta',
  path: '/consulta',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AppVentasIndexRoute = AppVentasIndexRouteImport.update({
  id: '/ventas/',
  path: '/ventas/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductosIndexRoute = AppProductosIndexRouteImport.update({
  id: '/productos/',
  path: '/productos/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventarioIndexRoute = AppInventarioIndexRouteImport.update({
  id: '/inventario/',
  path: '/inventario/',
  getParentRoute: () => AppRoute,
} as any)
const AdminTenantsIndexRoute = AdminTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AdminRoute,
} as any)
const AppProductosNuevoRoute = AppProductosNuevoRouteImport.update({
  id: '/productos/nuevo',
  path: '/productos/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppProductosProductIdRoute = AppProductosProductIdRouteImport.update({
  id: '/productos/$productId',
  path: '/productos/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppInventarioSalidaRoute = AppInventarioSalidaRouteImport.update({
  id: '/inventario/salida',
  path: '/inventario/salida',
  getParentRoute: () => AppRoute,
} as any)
const AppInventarioMovimientosRoute =
  AppInventarioMovimientosRouteImport.update({
    id: '/inventario/movimientos',
    path: '/inventario/movimientos',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventarioEntradaRoute = AppInventarioEntradaRouteImport.update({
  id: '/inventario/entrada',
  path: '/inventario/entrada',
  getParentRoute: () => AppRoute,
} as any)
const AdminTenantsNewRoute = AdminTenantsNewRouteImport.update({
  id: '/tenants/new',
  path: '/tenants/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsIdRoute = AdminTenantsIdRouteImport.update({
  id: '/tenants/$id',
  path: '/tenants/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/select-tenant': typeof SelectTenantRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/consulta': typeof AppConsultaRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/admin/tenants/new': typeof AdminTenantsNewRoute
  '/app/inventario/entrada': typeof AppInventarioEntradaRoute
  '/app/inventario/movimientos': typeof AppInventarioMovimientosRoute
  '/app/inventario/salida': typeof AppInventarioSalidaRoute
  '/app/productos/$productId': typeof AppProductosProductIdRoute
  '/app/productos/nuevo': typeof AppProductosNuevoRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/app/inventario/': typeof AppInventarioIndexRoute
  '/app/productos/': typeof AppProductosIndexRoute
  '/app/ventas/': typeof AppVentasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/select-tenant': typeof SelectTenantRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/consulta': typeof AppConsultaRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/admin/tenants/new': typeof AdminTenantsNewRoute
  '/app/inventario/entrada': typeof AppInventarioEntradaRoute
  '/app/inventario/movimientos': typeof AppInventarioMovimientosRoute
  '/app/inventario/salida': typeof AppInventarioSalidaRoute
  '/app/productos/$productId': typeof AppProductosProductIdRoute
  '/app/productos/nuevo': typeof AppProductosNuevoRoute
  '/admin/tenants': typeof AdminTenantsIndexRoute
  '/app/inventario': typeof AppInventarioIndexRoute
  '/app/productos': typeof AppProductosIndexRoute
  '/app/ventas': typeof AppVentasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/select-tenant': typeof SelectTenantRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/consulta': typeof AppConsultaRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/tenants/$id': typeof AdminTenantsIdRoute
  '/admin/tenants/new': typeof AdminTenantsNewRoute
  '/app/inventario/entrada': typeof AppInventarioEntradaRoute
  '/app/inventario/movimientos': typeof AppInventarioMovimientosRoute
  '/app/inventario/salida': typeof AppInventarioSalidaRoute
  '/app/productos/$productId': typeof AppProductosProductIdRoute
  '/app/productos/nuevo': typeof AppProductosNuevoRoute
  '/admin/tenants/': typeof AdminTenantsIndexRoute
  '/app/inventario/': typeof AppInventarioIndexRoute
  '/app/productos/': typeof AppProductosIndexRoute
  '/app/ventas/': typeof AppVentasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/admin'
    | '/app'
    | '/login'
    | '/select-tenant'
    | '/admin/users'
    | '/app/consulta'
    | '/app/onboarding'
    | '/admin/'
    | '/app/'
    | '/admin/tenants/$id'
    | '/admin/tenants/new'
    | '/app/inventario/entrada'
    | '/app/inventario/movimientos'
    | '/app/inventario/salida'
    | '/app/productos/$productId'
    | '/app/productos/nuevo'
    | '/admin/tenants/'
    | '/app/inventario/'
    | '/app/productos/'
    | '/app/ventas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/select-tenant'
    | '/admin/users'
    | '/app/consulta'
    | '/app/onboarding'
    | '/admin'
    | '/app'
    | '/admin/tenants/$id'
    | '/admin/tenants/new'
    | '/app/inventario/entrada'
    | '/app/inventario/movimientos'
    | '/app/inventario/salida'
    | '/app/productos/$productId'
    | '/app/productos/nuevo'
    | '/admin/tenants'
    | '/app/inventario'
    | '/app/productos'
    | '/app/ventas'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/admin'
    | '/app'
    | '/login'
    | '/select-tenant'
    | '/admin/users'
    | '/app/consulta'
    | '/app/onboarding'
    | '/admin/'
    | '/app/'
    | '/admin/tenants/$id'
    | '/admin/tenants/new'
    | '/app/inventario/entrada'
    | '/app/inventario/movimientos'
    | '/app/inventario/salida'
    | '/app/productos/$productId'
    | '/app/productos/nuevo'
    | '/admin/tenants/'
    | '/app/inventario/'
    | '/app/productos/'
    | '/app/ventas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SelectTenantRoute: typeof SelectTenantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select-tenant': {
      id: '/select-tenant'
      path: '/select-tenant'
      fullPath: '/select-tenant'
      preLoaderRoute: typeof SelectTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consulta': {
      id: '/app/consulta'
      path: '/consulta'
      fullPath: '/app/consulta'
      preLoaderRoute: typeof AppConsultaRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/ventas/': {
      id: '/app/ventas/'
      path: '/ventas'
      fullPath: '/app/ventas/'
      preLoaderRoute: typeof AppVentasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/productos/': {
      id: '/app/productos/'
      path: '/productos'
      fullPath: '/app/productos/'
      preLoaderRoute: typeof AppProductosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventario/': {
      id: '/app/inventario/'
      path: '/inventario'
      fullPath: '/app/inventario/'
      preLoaderRoute: typeof AppInventarioIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/tenants/': {
      id: '/admin/tenants/'
      path: '/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AdminTenantsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/productos/nuevo': {
      id: '/app/productos/nuevo'
      path: '/productos/nuevo'
      fullPath: '/app/productos/nuevo'
      preLoaderRoute: typeof AppProductosNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/productos/$productId': {
      id: '/app/productos/$productId'
      path: '/productos/$productId'
      fullPath: '/app/productos/$productId'
      preLoaderRoute: typeof AppProductosProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventario/salida': {
      id: '/app/inventario/salida'
      path: '/inventario/salida'
      fullPath: '/app/inventario/salida'
      preLoaderRoute: typeof AppInventarioSalidaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventario/movimientos': {
      id: '/app/inventario/movimientos'
      path: '/inventario/movimientos'
      fullPath: '/app/inventario/movimientos'
      preLoaderRoute: typeof AppInventarioMovimientosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventario/entrada': {
      id: '/app/inventario/entrada'
      path: '/inventario/entrada'
      fullPath: '/app/inventario/entrada'
      preLoaderRoute: typeof AppInventarioEntradaRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/tenants/new': {
      id: '/admin/tenants/new'
      path: '/tenants/new'
      fullPath: '/admin/tenants/new'
      preLoaderRoute: typeof AdminTenantsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants/$id': {
      id: '/admin/tenants/$id'
      path: '/tenants/$id'
      fullPath: '/admin/tenants/$id'
      preLoaderRoute: typeof AdminTenantsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTenantsIdRoute: typeof AdminTenantsIdRoute
  AdminTenantsNewRoute: typeof AdminTenantsNewRoute
  AdminTenantsIndexRoute: typeof AdminTenantsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTenantsIdRoute: AdminTenantsIdRoute,
  AdminTenantsNewRoute: AdminTenantsNewRoute,
  AdminTenantsIndexRoute: AdminTenantsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppConsultaRoute: typeof AppConsultaRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppInventarioEntradaRoute: typeof AppInventarioEntradaRoute
  AppInventarioMovimientosRoute: typeof AppInventarioMovimientosRoute
  AppInventarioSalidaRoute: typeof AppInventarioSalidaRoute
  AppProductosProductIdRoute: typeof AppProductosProductIdRoute
  AppProductosNuevoRoute: typeof AppProductosNuevoRoute
  AppInventarioIndexRoute: typeof AppInventarioIndexRoute
  AppProductosIndexRoute: typeof AppProductosIndexRoute
  AppVentasIndexRoute: typeof AppVentasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConsultaRoute: AppConsultaRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppIndexRoute: AppIndexRoute,
  AppInventarioEntradaRoute: AppInventarioEntradaRoute,
  AppInventarioMovimientosRoute: AppInventarioMovimientosRoute,
  AppInventarioSalidaRoute: AppInventarioSalidaRoute,
  AppProductosProductIdRoute: AppProductosProductIdRoute,
  AppProductosNuevoRoute: AppProductosNuevoRoute,
  AppInventarioIndexRoute: AppInventarioIndexRoute,
  AppProductosIndexRoute: AppProductosIndexRoute,
  AppVentasIndexRoute: AppVentasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SelectTenantRoute: SelectTenantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
